import: [complex, generative_model]
job.type: train
dataset.name: toy


model: generative_model

valid.filter_with_test: True
valid.every: 1

train:
  loss: kl
  type: generative
  optimizer: Adagrad
  optimizer_args:
    lr: 0.6
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    mode: max
    patience: 4
  max_epochs: 50
  batch_size: 128
eval.metrics_per.head_and_tail: True
eval.chunk_size: 100

lookup_embedder.regularize_weight: 0.00001


