job.type: train
dataset.name: zero-shot-head-10
eval.filter_with_test: false
valid.metric: mean_reciprocal_rank_filtered
valid.every: 1
entity_ranking.metrics_per.head_and_tail: True
train:
  optimizer: Adagrad
  optimizer_args:
    lr: 0.2
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    mode: max
    patience: 4
  split: train_aux

model: complex
lookup_embedder:
  dim: 100
  regularize_weight: 0.8e-7
  initialize: normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.1
