job.type: train
dataset.name: toy

train:
  loss: kl
  type: 1vsAllProbab
  optimizer: Adagrad
  optimizer_args:
    lr: 0.4
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    mode: max
    patience: 4
  max_epochs: 100

1vsAllProbab:
  reparameterize_samples: 2
  # set to -1 to learn prior variances for every entity/relations
  prior_variance: -1
  elbo_form: ent
  norm_p: 3


valid.filter_with_test: True
valid.every: 5
model: probabilistic_model
probabilistic_embedder.dim: 41

