job.type: train
dataset.name: toy
valid.every: 1
train:
  type: 1vsAll
  optimizer: Adagrad
  optimizer_args:
    lr: 0.2
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    mode: max
    patience: 10
  batch_size: 100

model: factor

factor:
  # a key in dataset.files with type=attributes
  feature_file: train_entity_numeric
  features_as_indicator: True

lookup_embedder:
  dim: 100
  regularize_weight: 0.8e-7
  initialize: normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.1
