dataset.name: zero-shot-head-10
job.type: zero_shot
zero_shot:
  only_eval: False
  full_model_checkpoint: local/thesis/zero-shot-experiments/head-10/train-on-validAndAux/complex-1vsAll-kl/checkpoint_best.pt

  #{fold_in, closed_form, similarity}
  type: similarity
  obtain_seen_model: load
  # {all, incremental}
  eval_type: incremental
  # remote
  #seen_checkpoint: local/zero-shot-experiments/zero-shot-subject-10/checkpoint_best_complex_mr.pt
  # local
  seen_checkpoint: local/zero-shot-experiments/head-10/fold-in/checkpoint_best_complex_1vsAll_kl.pt
  #seen_checkpoint: local/experiments/checkpoint_best_distmult.pt

  fold_in:
    num_epoch: -1

valid.every: 3
train.max_epochs: 5

model: complex
lookup_embedder:
  dim: 100
  regularize_weight: 0.8e-7
  initialize: normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.1

train:
  optimizer: Adagrad
  optimizer_args:
    lr: 0.2
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    mode: max
    patience: 4
