dataset.name: zero-shot-head-10
job.type: zero_shot
zero_shot:
  type: closed_form
  obtain_seen_model: load
  # remote
  #seen_checkpoint: local/zero-shot-experiments/zero-shot-subject-10/checkpoint_best_distmult.pt
  # local
  seen_checkpoint: local/experiments/checkpoint_best_distmult.pt

valid.every: 3
train.max_epochs: 5


model: complex
lookup_embedder:
  dim: 100
  regularize_weight: 0.8e-7
  initialize: normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.1

train:
  optimizer: Adagrad
  optimizer_args:
    lr: 0.2
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    mode: max
    patience: 4
